::: {.tabdiv}

```{r}
# Load/set options ----
includeCSS("www/custom_inputs/customTreeInput.css")
includeScript("www/custom_inputs/customTreeInput.js")
includeCSS("www/custom_inputs/layerStyleInput.css")
includeScript("www/custom_inputs/layerStyleInput.js")
source("scripts/custom_inputs/customTreeInput.R")
source("scripts/custom_inputs/layerStyleInput.R")
suppressPackageStartupMessages(library(dplyr))
habitat_db <- arrow::open_dataset("data/habitat_db.parquet")
diversity_db <- arrow::open_dataset("data/diversity_db.parquet")
sel_habs <- habitat_db |>
  collect() |>
  tidyr::unnest(files) |>
  filter(type == "binary", scenario == "current", threshold == "p10", post_treatment == "const")
sel_habs <- bind_rows(sel_habs, data.frame(habitat_name = "EUSEAMAP2025 (simplified)", file = "data/euseamap2025_simplified.gpkg"))
lcbd <- diversity_db |>
  collect() |>
  tidyr::unnest(files) |>
  filter(scenario == "current", threshold == "p10", post_treatment == "const", metric == "lcbd")
richness <- diversity_db |>
  collect() |>
  tidyr::unnest(files) |>
  filter(scenario == "current", threshold == "p10", post_treatment == "const", metric == "richness", type == "continuous")
atlas_data <- data.frame(
  group = c(rep("Species formed habitats", nrow(sel_habs))#, rep("Diversity", nrow(lcbd)), rep("Diversity", nrow(richness))
  ),
  layer = c(sel_habs$habitat_name#, paste(lcbd$metric_name, "-", stringr::str_to_title(lcbd$group)), paste(richness$metric_name, "-", stringr::str_to_title(richness$group))
  ),
  file = c(sel_habs$file#, lcbd$file, richness$file
  )
)
un_groups <- unique(atlas_data$group)
choices_list <- lapply(un_groups, \(x) {
  atlas_data$layer[atlas_data$group == x]
}) 
names(choices_list) <- un_groups
rm(habitat_db, diversity_db, sel_habs, lcbd, richness)

#choices_list$`RBA (available soon)` <- c("Available soon")

choices_list$`Blue Carbon` <- c("EURO-CARBON points")

choices_list$MSP <- c("MPA Europe regions", "MPA - Level of protection")

choices_list$Prioritisation <- c(
  "Prioritisation for Biodiversity Conservation - RBA",
  "Prioritisation for Biodiversity Conservation - RBA - Top 10%",
  "Prioritisation for Biodiversity Conservation - RBA - Top 30%",
  "Prioritisation for Biodiversity Conservation - RBA - Top 50%",
  "Priority areas for commercial fish - RBA",
  "Priority areas for commercial fish - RBA - Top 10%",
  "Priority areas for commercial fish - RBA - Top 30%",
  "Priority areas for commercial fish - RBA - Top 50%"
)

choices_list$Physical <- c(
  "Bathymetry", "Rugosity", "Seafloor geomorphic features", "Seabed slope",
    "Wave fetch", "Current speed", "River runoff", "Distance to coast"
)

choices_list$`Temperature/Chemical` <- c(
  "Sea surface temperature", "Sea bottom temperature", "Air temperature", "Salinity", "pH", "Oxygen concentration",
  "Sea ice cover", "Phytoplankton concentration", "Mixed layer depth", "Nitrate concentration", "Phosphate concentration",
  "Diffuse attenuation coefficient", "Photosynthetically active radiation"
)
```


``` {r}
tree_input <- htmltools::div(
  customTreeInput(
    inputId = "atlasSelector",
    label = "Select Options (only one per group):",
    choices = choices_list
  ), id = "atlasSelectorDiv"
)

layerstyle_input <- htmltools::div(
  layerStyleInput(
    inputId = "atlasLayerStyle",
    label = "Configure Layer Styles (click on 'Apply styles' to apply changes):",
    layers = c("Habitat", "Diversity", "Blue Carbon", "MSP", "Prioritisation", "Physical", "Temperature/Chemical"),
    default_alpha = 0.8,
    default_palette = "Blues"
  ), id = "atlasLayerSelectorDiv"
)

htmltools::tags$div(
  id = "atlasTabs",
  htmltools::tags$div(
    class = "panel-tabset",
    # --- Nav tabs ---
    htmltools::tags$ul(
      class = "nav nav-tabs",
      role = "tablist",
      htmltools::tags$li(
        class = "nav-item",
        role = "presentation",
        htmltools::tags$a(
          class = "nav-link active",
          id = "tabset-2-1-tab",
          "data-bs-toggle" = "tab",
          "data-bs-target" = "#tabset-2-1",
          role = "tab",
          "aria-controls" = "tabset-2-1",
          "aria-selected" = "true",
          href = "",
          "Layers"
        )
      ),
      htmltools::tags$li(
        class = "nav-item",
        role = "presentation",
        htmltools::tags$a(
          class = "nav-link",
          id = "tabset-2-2-tab",
          "data-bs-toggle" = "tab",
          "data-bs-target" = "#tabset-2-2",
          role = "tab",
          "aria-controls" = "tabset-2-2",
          "aria-selected" = "false",
          href = "",
          tabindex = "-1",
          "Styling"
        )
      )
    ),
    # --- Tab content ---
    htmltools::tags$div(
      class = "tab-content",
      htmltools::tags$div(
        id = "tabset-2-1",
        class = "tab-pane active",
        role = "tabpanel",
        "aria-labelledby" = "tabset-2-1-tab",
        tree_input
      ),
      htmltools::tags$div(
        id = "tabset-2-2",
        class = "tab-pane",
        role = "tabpanel",
        "aria-labelledby" = "tabset-2-2-tab",
        layerstyle_input
      )
    )
  )
)

```


<div class="bottom-container"> 
::: {.grid .gridaltsm}

::: {.g-col-5}
```{r}

```
:::

::: {.g-col-4}
```{r}

```

:::

::: {.g-col-3}
```{r}

```

:::

:::
</div>

<div class="context-icons">

```{r}
button <- htmltools::tags$span(
  bsicons::bs_icon("download"),
  "DOWNLOAD THE DATA",
  style = "color: #545454 !important;"
)
htmltools::div(
  actionLink("downloadDataSpecies", label = button),
  class = "context-icons-box"
)
```

<div class="context-icons-box" onclick="location.href='https://github.com/iobis/mpaeu_sdm/blob/main/codes/model_fit.R';">{{< fa brands github >}} ACCESS THE CODE</div>

```{r}
button <- htmltools::tags$span(
  bsicons::bs_icon("play-fill"),
  "RUN THE MODEL",
  style = "color: #545454 !important;"
)
htmltools::div(
  actionLink("runModelSpecies", label = button),
  class = "context-icons-box"
)
```

</div>


:::