::: {.tabdiv}

```{r}
# Load/set options ----
# Load metrics options
metrics_options <- c("Select a metric" = "", "Richness" = "richness")

# Add selectors ----
# Filter selector
selectInput(
   inputId = "diversitySelect",
   label = "Select metric", 
   choices = metrics_options
)

selectInput(
   inputId = "diversityGroup",
   label = "Select level", 
   choices = c("Select one" = "")
)

# Add contextual information ----
tags$div(
  id = "diversity_title",
  class = "rtitle_class",
  textOutput("selectedMetric"),
  style = "font-style: normal !important;"
)

tags$div(
  id = "context_info_div",
  class = "context_info",
  textOutput("contextMetric"), htmltools::br()
)

conditionalPanel("input.diversitySelect == 'richness' && input.modelSelectDiversity != 'raw'",
tags$div(
  id = "scenario_box_diversity",
  class = "scenario_class",
      selectInput(
        inputId = "diversityType",
        label = "Map type",
        choices = c("Sens+Spec" = "max_spec_sens", "P10" = "p10", "MTP" = "mtp")
      ))
)

conditionalPanel("input.diversitySelect == 'richness' && input.modelSelectDiversity == 'raw'",
tags$div(
  id = "scenario_box_diversity",
  class = "scenario_class",
      selectInput(
        inputId = "diversityTypeRaw",
        label = "Map type",
        choices = c("Aggregated" = "aggregated", "Original" = "original")
      ))
)

conditionalPanel("input.diversitySelect == 'richness' && input.modelSelectDiversity != 'raw'",
tags$div(
  id = "scenario_box_diversity",
  class = "scenario_class",
      selectInput(
        inputId = "diversityMode",
        label = "Mode",
        choices = c("Binary" = "bin", "Continuous" = "cont")
      )))
```

<div class="bottom-container"> 
::: {.grid .gridaltsm}

::: {.g-col-5}
```{r}
tags$div(
  id = "scenario_box_diversity",
  class = "scenario_class",
selectInput(
        inputId = "modelSelectDiversity",
        label = "Model",
        choices = c("Raw" = "raw", "RandomForest" = "rf", "MAXENT" = "maxent", "XGBoost" = "xgboost", "Ensemble" = "ensemble")
      ))
```
:::

::: {.g-col-4}
```{r}
tags$div(
  id = "scenario_box_diversity",
  class = "scenario_class",
      selectInput(
        inputId = "scenarioSelectDiversity",
        label = "Scenario",
        choices = scenario_options
      ))
```

:::

::: {.g-col-3}
```{r}
tags$div(
  id = "scenario_box_diversity",
  class = "scenario_class",
      selectInput(
        inputId = "periodSelectDiversity",
        label = "Period",
        choices = period_options
      ))
```

:::

:::
</div>

<div class="context-icons">

```{r}
button <- htmltools::tags$span(
  bsicons::bs_icon("download"),
  "DOWNLOAD THE DATA",
  style = "color: #545454 !important;"
)
htmltools::div(
  downloadLink("downloadDataDiversity", label = button),
  class = "context-icons-box"
)
```

<div class="context-icons-box" onclick="location.href='https://github.com/iobis/mpaeu_sdm/blob/main/codes/post_div_richness.R';">{{< fa brands github >}} ACCESS THE CODE</div>

</div>

:::