::: {.tabdiv}

```{r}
# Load/set options ----
# Load habitat options
hab_options <- c("Select a habitat" = "",
 "Seagrass" = "seagrass", "Polychaete reefs" = "polychaete_reefs",
 "Maerl" = "maerl", "Kelp" = "kelp", "Corals" = "corals",
 "Bivalves beds" = "bivalves_beds")

# Add selectors ----
# Filter selector
selectInput(
   inputId = "habitatSelect",
   label = "Select habitat", 
   choices = hab_options
)

selectInput(
   inputId = "habitatBin",
   label = "Threshold", 
   choices = c("P10" = "p10", "MSS" = "mss")
)

label_switch_eunis <- bslib::tooltip(span("Show EUNIS biogenic map", bsicons::bs_icon("info-circle", size = "0.7em")),
       "Show EUNIS biogenic substrate according to EMODnet Seabed Habitats product (https://emodnet.ec.europa.eu/en/seabed-habitats). Not available at this moment.",
        placement = "bottom")
span(bslib::input_switch("habitatEUNIS", label_switch_eunis, FALSE), style = "display: flex; margin-top: 25px; margin-bottom: 5px; margin-left: 5px;")

label_switch_bin <- bslib::tooltip(span("Show binary", bsicons::bs_icon("info-circle", size = "0.7em")),
       "Show maps in fully binary (presence/absence) mode. Otherwise, just removes the lower limit according to the metric on the 'Binary mode' selector.",
        placement = "bottom")
span(bslib::input_switch("habitatBinaryFull", label_switch_bin, FALSE), style = "display: flex; margin-top: 2px; margin-bottom: 5px; margin-left: 5px;")

# Add contextual information ----
tags$div(
  id = "habitat_title",
  class = "rtitle_class",
  textOutput("selectedHabitat"),
  style = "font-style: normal !important;"
)

tags$div(
  id = "context_info_hab",
  class = "context_info",
  uiOutput("contextHabitat")
)
```

<div class="bottom-container"> 
::: {.grid .gridaltsm}

::: {.g-col-5}
```{r}
tags$div(
  class = "scenario_class",
  selectInput(
        inputId = "modelSelectHabitat",
        label = "Post-treatment",
        choices = c("Standard" = "std", "Constrained" = "const")
      ))
```
:::

::: {.g-col-4}
```{r}
tags$div(
  class = "scenario_class",
      selectInput(
        inputId = "scenarioSelectHabitat",
        label = "Scenario",
        choices = scenario_options
      ))
```

:::

::: {.g-col-3}
```{r}
tags$div(
  class = "scenario_class",
      selectInput(
        inputId = "periodSelectHabitat",
        label = "Period",
        choices = period_options
      ))
```

:::

:::
</div>

<div class="context-icons">

```{r}
button <- htmltools::tags$span(
  bsicons::bs_icon("download"),
  "DOWNLOAD THE DATA",
  style = "color: #545454 !important;"
)
htmltools::div(
  downloadLink("downloadDataHabitat", label = button),
  class = "context-icons-box"
)
```

<div class="context-icons-box" onclick="location.href='https://github.com/iobis/mpaeu_sdm/blob/main/codes/post_habitat.R';">{{< fa brands github >}} ACCESS THE CODE</div>

</div>

:::